# Generated by Django 3.2.7 on 2021-10-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieData', '0002_rename_moviedata_netflixmoviedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetflixMovieData',
        ),
    ]
